export const GET_ARTICLES_DATA = 'GET_ARTICLES_DATA';
export const GET_ARTICLES_DATA_SUCCESS = 'GET_ARTICLES_DATA_SUCCESS';
export const GET_ARTICLES_DATA_FAILURE = 'GET_ARTICLES_DATA_FAILURE';
export const GET_ARTICLE_DETAILS = 'GET_ARTICLES_DETAILS';
export const GET_ARTICLE_DETAILS_SUCCESS = 'GET_ARTICLES_DETAILS_SUCCESS';
export const GET_ARTICLE_DETAILS_FAILURE = 'GET_ARTICLES_DETAILS_FAILURE';